global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ai-processing"
    metrics_path: /metrics
    static_configs:
      - targets: ["ai:8001"]
        labels:
          service: "lumineer-ai"

  - job_name: "qdrant"
    metrics_path: /metrics
    static_configs:
      - targets: ["qdrant:6333"]
        labels:
          service: "qdrant"

  - job_name: "postgres"
    metrics_path: /metrics
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "postgres"
